export const USUARIOS_TEXTS = {
  header: {
    title: 'Agentes Inmobiliarios',
    welcome: 'Bienvenido,',
    logoutButton: 'Cerrar Sesión',
    navInmuebles: 'Inmuebles',
    navAgents: 'Agentes',
  },
  list: {
    loading: 'Cargando agentes...',
    empty: 'No hay agentes registrados en la plataforma',
    error: 'Ocurrió un error al cargar la lista de agentes',
    statusActive: 'Activo',
    statusInactive: 'Inactivo',
  },
  pagination: {
    pageLabel: 'Página',
    ofLabel: 'de',
  },
  profile: {
    title: 'Mi Perfil',
    nameLabel: 'Nombre',
    namePlaceholder: 'Tu nombre completo',
    emailLabel: 'Correo Electrónico',
    emailPlaceholder: 'tu@correo.com',
    passwordLabel: 'Nueva Contraseña',
    passwordPlaceholder: 'Dejar vacío para no cambiar',
    saveButton: 'Guardar Cambios',
    saving: 'Guardando...',
    deleteButton: 'Eliminar Cuenta',
    deleteConfirm: '⚠️ Esta acción es irreversible. Se eliminarán tu cuenta y todos tus inmuebles en estado Disponible o Reservado. ¿Confirmas?',
    successMessage: 'Perfil actualizado correctamente',
    memberSince: 'Miembro desde',
  },
} as const;
